pr: none
trigger: none

strategy:
  matrix:
    A:
      one: 'a-one'
    B:
      two: 'b-two'
    C:
      one: 'c-one'
      two: 'c-two'

steps:

- checkout: self
  fetchDepth: 0

- template: template.yml
  parameters:
    one: $[ variables['one'] ]
    two: $[ variables['two'] ]

## condition works:
##   Job A script ran because eq(coalesce(variables.one, 'literal-one'), variables.one)
##   Job B script did not run because 'variables.one' evaluated to Null
## env vars don't work:
##   Job A
##     ONE: a-one
##     TWO: $[ coalesce(variables.two, 'literal-two') ]
##   Job B
##     ONE: $[ coalesce(variables.one, 'literal-one') ]
##     TWO: b-two
## ==================================
# - script: |
#     echo "ONE: $ONE"
#     echo "TWO: $TWO"
#   displayName: Use matrix vars in runtime expr
#   condition: eq(coalesce(variables.one, 'literal-one'), variables.one)
#   env:
#     ONE: $[ coalesce(variables.one, 'literal-one') ]
#     TWO: $[ coalesce(variables.two, 'literal-two') ]
## ==================================
