pr: none
trigger: none

variables:
  DisableDockerDetector: true
  which: A2
  continue: true

stages:

- stage: A
  dependsOn: []
  jobs:

  - job: A1
    condition: eq(variables.which, 'A1')
    steps:

    - script: |
        echo "##vso[task.setvariable variable=continue;isOutput=true]$(continue)"
        echo "##vso[task.setvariable variable=value;isOutput=true]A1"
      name: get

  - job: A2
    condition: eq(variables.which, 'A2')
    steps:

    - script: |
        echo "##vso[task.setvariable variable=value;isOutput=true]A2"
      name: get

- stage: B
  dependsOn: A

  condition: eq(stageDependencies.A.A1.result, 'Skipped')
    # and(
    #   succeeded(),
    #   or(
    #     eq(stageDependencies.A.A1.result, 'Skipped'),
    #     eq(dependencies.A.outputs['A1.get.continue'], 'true')
    #   )
    # )
  
  variables:
    stagedeps: $[ convertToJson(stageDependencies) ]
    deps: $[ convertToJson(dependencies) ]
    vars: $[ convertToJson(variables) ]
    ${{ if eq(variables['which'], 'A1') }}:
      value: $[ stageDependencies.A.A1.outputs['get.value'] ]
    ${{ else }}:
      value: $[ stageDependencies.A.A2.outputs['get.value'] ]
  
  jobs:

  - job: B1
    steps:

    - script: |
        echo 'Value is [$(value)]'
        echo $'stageDependencies:\n$(stagedeps)\n\n'
        echo $'dependencies:\n$(deps)\n\n'
        echo $'variables:\n$(vars)\n\n'
